addons:
  apt:
    packages:
    - realpath
language: python
services: docker
env:
  global:
  - GITHUB_USER=joeblackwaslike
  - GITHUB_ORG=joeblackwaslike
  - DOCKER_USER=joeblackwaslike
  - DOCKER_ORG=joeblackwaslike
  # DOCKER_PASS
  - secure: "ZdJ8Im0vOwPYDLOsYYb8zA/1Sxouf9ugDE6H+nbIhJjOvdqm6R/02qjksG76QapAc4dMSjwD4xbyvqGDDlQrvYEd2J96pmnKd0l7VZ3I6/ndtdFsJz4QzWPDzimu3YmHPmaLtyZJsmPqZCqHcGmLLN+q05XOgzzmrvOhBpKrLAzoqWx05rUOsQsrjvF+ZzfyfQ+5tBsHVL5crSOfEV3K0Et5RSG9QgZhrX8KqC8JF5j01/v1O2H9gdzfpPdW/8+U5gxv6a9SX8/Cbb8E3tFE3emHmYUjPaHx9Kj+Zc17w0w5VpcmTvvjuxHmLwBMjgrBEVEvYdiSwjYZzlGAVVtb7Rvuitlw9MyFl9Cl0tjpXG1B5Wi9Ivg+T8lCMchHF6ulkxttJ6cyQnJRSVYqm7/ZJAr0HHWAusHwyFtfcfCrw2GvS9J6Ei1QwGGg5HrlraCE924AASJyIevWFXUDm4+Y9st8YVvZ96kyZSjbzGY8glEBuFfg0egfU3wtn+KvQJDqIXicO0ZffxaqWatAJCbZhEY0B7/RmGbgoLzD10vj/KUTvtNZ+UImuCwO2/tHgWE3FbzrA2wTrKB4zKjIlodx2mRNbRZdcBgoEfspi3mZA4QIzC8rNhhWr+xvA+waVO6zAYk7TUhap86x2x5rgqsYSQYlsNnXnrBY+ilm5+itYQM="
notifications:
  email:
    on_success: never
    on_failure: always

before_install: source scripts/ci/environment.sh

install: make build

script: make test

after_success:
- ci-tag-build
- hub-push
- hub-update-readme
