addons:
  apt:
    packages:
    - realpath
language: python
services: docker
env:
  global:
  - GITHUB_USER=joeblackwaslike
  - GITHUB_ORG=joeblackwaslike
  - DOCKER_USER=joeblackwaslike
  - DOCKER_ORG=joeblackwaslike
  # DOCKER_PASS
  - secure: "TTRJikt2fkneGes9+r8vproiB4pnKsRLKpVCpJAGy+7AouvK32Z/5kALYlc6xuNQkX5O2YDbqitH0bxXr8iJWATB8rL1d0ETfnn9qmqFZWhv7tVae2eQh2MFgwUidnDSp/aMUwlZvxefCvpV6iNOFVoZuRmQbbckBf1Ed2WQ1n4b2DfeZl2hMVpYa7VTI5jjjWyuXP74gG3l3kaqaMYWWGci2LJFOLWVBFKEn+DXigMyZtm0WRJD19YeHHgn8mf2Pv9o9d7SmqETfoI0R3tVWVWBj3eChLsv18vcJhVk0vs2sxAXFEUa2EmIwKKd8gslNUPTDClszUMG4hXTw99XxAP3DvMZe3iWOJOFpAQX0S52mM60ayW1+utBFEtOug51Z/740xi2CAdQ30vNjlBR1XS1+Nata7zyFP67PNZfDsAup5u9eJ/7VM/7VbVP1WeBTARjKZc6oyHpOjo3PGHsfGz1he+H1dopMNOnV1V6HPwdcQEUh4HsgR1s36ERl2z+YeSgMUjYsPz4lEi+uZFKSDQaZ4Y4qebrrdjP+rW/qyCTkwNC7M9kjUgUa3d2AVh1jMJPEnXz3C7FfWWlqpwaDi8shOJu4apX6SecJ1nUOqQ8O//jVDuYxq76wrcpjxm14aQ5Qr2L4fd6AmByMbgo7XxDBBMSmtBMg5HSev2ob10="
notifications:
  email:
    on_success: never
    on_failure: always

before_install: source scripts/ci/environment.sh

install: make build

script: make test

after_success:
- ci-tag-build
- hub-push
- hub-update-readme
