---
target: Makefile
---
{% set github_user = data.get('vars')['github']['user'] -%}
{% set github_org = data.get('vars')['github']['org'] -%}
{% set docker_user = data.get('vars')['docker']['user'] -%}
{% set docker_org = data.get('vars')['docker']['user'] -%}

SHELL := /bin/bash

GITHUB_USER ?= {{ github_user }}
GITHUB_ORG ?= {{ github_org }}
GITHUB_REPO := docker-dgoss
GITHUB_TAG = $(shell git tag | sort -n | tail -1)

DOCKER_USER ?= {{ docker_user }}
DOCKER_ORG ?= {{ docker_org }}
DOCKER_REPO := dgoss
DOCKER_TAG := latest
DOCKER_IMAGE := $(DOCKER_ORG)/$(DOCKER_REPO):$(DOCKER_TAG)

.PHONY: all build build-test templates test push-image

all: build test

build:
	docker build --force-rm -t $(DOCKER_IMAGE) .

build-test:
	tests/edit $(DOCKER_IMAGE) tail -f /dev/null

templates:
	tmpld --data=templates/vars.yaml templates/*.j2

test:
	tests/run $(DOCKER_IMAGE) tail -f /dev/null

push-image:
	if [[ $(TRAVIS) == 'true' ]]; then \
		docker login -u $(DOCKER_USER) -p $(DOCKER_PASS); \
	fi
	docker push $(DOCKER_IMAGE)
